### ISSUE TITLE
some  bug and advice

### ISSUE THREAD

**Issue by SuperSmileForever** [Synthetify/synthetify-protocol#12]
1. The first bug: when I clicked the "Connect Wallet" button, I selected the "Extension Mode", but the program switched to the "Webpage Wallet" button. This is a bug. For the security of funds, I have multiple Sollet wallets, which can be easily switched with extension
2. A little advice: the UI pages of Deposit and Mint have too many pop-up Windows, some of which block some content. Maybe I have some obsessive-compulsive disorder

**Comment by wojciech-cichocki** [comment]
Problem solved. Thanks for opening the issue.
