### ISSUE TITLE
Unnecessary error logs

### ISSUE THREAD

**Issue by armaniferrante** [Synthetify/synthetify-protocol#7]
The latest version of Anchor will automatically log `#[error]` `#[msg(...)]`s on program exit. Example here https://github.com/Synthetify/synthetify-protocol/blob/master/programs/exchange/src/lib.rs#L60.

**Comment by armaniferrante** [comment]
This is actually only true for non-state instructions. Will be true for all instructions in the next release, however. Related https://github.com/project-serum/anchor/pull/194.

**Comment by NorbertBodziony** [comment]
Thank you. Program upgraded to Anchor v0.4.4 and redundant Error logs removed.
