### ISSUE TITLE
init seeds should specify the bump parameter

### ISSUE THREAD

**Issue by armaniferrante** [Synthetify/synthetify-protocol#71]
When creating a PDA via init seeds https://github.com/Synthetify/synthetify-protocol/blob/master/programs/exchange/src/lib.rs#L1775, one should specify the `bump = ` param, which will check that the bump given is the canonical bump, i.e., the one returned by find_program_address.

**Comment by NorbertBodziony** [comment]
Fixed in current master.

**Comment by pindaroso** [comment]
Ty sers. Saving this for later.
