### ISSUE TITLE
Bump should be explicitly provided

### ISSUE THREAD

**Issue by armaniferrante** [Synthetify/synthetify-protocol#84]
This will not compile in the next version of Anchor. The bump must be explicitly provided. This was changed so that a check can be done on PDA initialization that the "canonical" bump is used (i.e. the bump returned by find_program_address) https://github.com/Synthetify/synthetify-protocol/blob/master/programs/exchange/src/context.rs#L317.

**Comment by NorbertBodziony** [comment]
fixed.
